= Bonfiglioli & Jáuregui - El complejo dacístico-teatral de la Conquista

https://www.youtube.com/watch?v=iP82uRvWhkI

== Nueve conquistas mexicanas

== ¿Danza de moros y cristianos o danza de conquista?

.Consideraciones teóricas (p.11)
* «Los procesos históricos "reales" y los hechos simbólicos actuales (Mediterráneo, Andes, América Central, México) manifiestan una misma estructura conflictiva». En este enunciado se abordan varios conceptos importantes para la teoría social estructuralista:
** La relación entre "proceso" y "estructura", la segunda manifestada por el primero
** "Historia" y "actualidad", manifestando una misma estructura
** La capacidad de la "estructura" para manifestar un conflicto social
* «Elementos transformacionales» que «conducen» al «núcleo analítico»

.Premisas analíticas (p. 11-12)
* Dos análisis distintos, correspondientes a dos «variantes temáticas» de un mismo complejo argumental
* «Al unificar variantes y formas distintas de representar un mismo macro-tema, [se puede] hablar de una sola categoría, que denominamos _danzas de conquista_»

.Proceso histórico (p. 11-12)
* Modelos de confrontación ritual (mesoamericanos)
** Hombre contra Jaguar-tigre
** Combates ritualizados entre bandos humanos
* "Cultura de conquista"
** Juego de cañas
** Corridas de toros
** Incorporación de elementos y personajes indígenas
** Conflictos bíblicos
** Ceremoniales carnavalescos
** Teatralización de la Conquista (mascarada sin parlamento)
** «En algunas pastorelas se ha puesto particular atención al combate de Luzbel y los soldados de Herodes, por un lado, contra el ángel, los pastores y los reyes, por el otro» (p. 16)
* «Desplazamiento del eje naturaleza-cultura al eje intercultural» (p. 13)
* «Posible vínculo con la tercera raíz mexicana, la de los negros» (p. 19)

== Problemas de definición (p. 12-13)

* "Rasgos constitutivos mínimos" ("núcleo dancístico-teatral")
** «La formación de dos grupos cuyo antagonsimo se fudnamenta --por medio de la escenificación de un combate-- en la conquista, recuperación o defensa de un territorio»
* Semántica fuerte/débil (p. 13)

.Confrontación
. De carácter étnico y religioso
. Representación épica-militar
* «División dualista» (generalidad) / «Particularidad estructural»
* relaciones históricas vs. transformaciones de sistema
** [jaguar : toro :: indígena : español] :: naturaleza : cultura
** jaguar-naturaleza -> jaguar-cultura (p. 13)
* Reciprocidad entre bandos (comparten sistema de valores y reglas): relación complementaria a la de confrontación
* Dualismo y trialismo (p. 14)

== Los matices mexicanos (p. 15)
* Moros : indígenas de antes
* Cristianos : mestizos : indígenas de hoy
* Mexicanización/Occidentalización (Concheros)
* Diablos : Judíos : Fariseos : Borrados : Moros (p. 16)
** Ligados a la risa y la transgresión cómico-sexual
*** «no sólo se asocia a la diversión, sino que ésta es al mismo tiempo una prefiguración simbólica del peligro» (p. 18)
*** «debe ser interpretada como un importante poder ofensivo del enemigo, quien, como tal, se atribuye el derecho de violar las normas éticas de su contrincante»
** Conquista -> Pasión
** Judas : Mahoma

.Santiago
