// = González & Camacho - La música del maíz: estudio etnomusicológico desde una perspectiva semiológica en la región Huasteca
:Author: Guillermo Mora Reguera
:Email: <guillermo.mora@fam.unam.mx>
:Date: noviembre 2020 - septiembre 2021
:Revision: 2
:toc:

// Seminario de Semiología Musical: Uno de nuestros objetivos primordiales es llevar a cabo un estudio de la significación del discurso musical a partir del análisis de la relación entre música, estructuras y cultura en el caso concreto de un ritual agrícola.

== [Introducción]

=== [Objetivos]
* ¿En qué se basa la "representatividad" de las tradiciones? Y ¿por qué la comunidad de Chilocuil tiene este atributo?
* Estructuras y gramática generativa

=== [Hipótesis]
* Función sígnica de las formas musicales
* Enlaces entre conceptos y música hispánica y cosmovisión mesoamericana

=== Teoría

.Epistemología semiológica
** Estructuras musicales
** Gramática generativa del género musical
** Discurso sonoro (?)
** Producción simbólica

.Hjelmslev

* [Dimensiones]
** Música
** Espacio (fijos, semi-fijos y dinámicos)
*** Objetos sagrados
*** Locaciones
** Tiempo

* *Relaciones* de la música
** de *Posicionamiento* frente a
*** Otros elementos como
**** Objetos sagrados
**** Espacios o locaciones
**** Integrantes
**** Actos
** de *Dependencia* entre los anteriores +
¿El cambio de los dos últimos conlleva obligadamente un cambio en la primera?

* Texto (ritual)
** Estructura del objeto de estudio en su totalidad
** Desglose [segmentación] de sus componentes (secuencias, partes, elementos)

* Funtivos
** Música: se encuentra en relación de dependencia con otros elementos; es decir, es un funtivo:
*** Constante, cuya presencia es imprescindible para el otro funtivo
*** Variable, cuya presencia no es necesaria para otro funtivo

* Conmutación
** Análisis de las distintas expresiones musicales en diferentes contextos

IMPORTANT: ¿Cuál es el aporte del marco teórico-conceptual lingüístico de Hjelmslev al estudio de la música en contextos rituales?

.Chilocuil
* [Objeto de estudio en la tesis de lic. de L. Alegre]
* Grupos étnicos: nahuas, tenek, totonacos, tepehuas, ñanúu y pames

// .Metodología
// * Diferencias y similitudes inter-regionales
// * «Base fundamental»
// ** Simbología
// ** Manifestaciones musicales vinculadas
// * Segmentación del ritual

****
.. ¿Un "discurso", no contiene en sí mismo la información primaria? Contrario a la música, cuya significación es toda contextual
.. La mitología verbal y no-verbal, y una subordinación implícita de la segunda a la primera en *Lévi-Strauss, C. - El hombre desnudo (Mitológicas IV)*
****

== [Etnografía]

.Tlamanes
* Ceremonial del maíz
* Calendario ritual
** Siembra (abril - mayo)
** cosecha (octubre - noviembre)
* Dirigido a los "Señores de Abajo/Tierra" (pedir permiso)
* Su función es «abrir el tiempo y el espacio sagrados, permitiendo establecer contacto con el mundo divino»
* En el ritual de siembra no se acompaña con música la procesión, en el de cosecha sí

.Canarios
* Música única del ritual (?)
* Documental
** Origen hispánico, africano, mexicano
** S. XV
* Cantos a los Señores Tierra
* Oración (comunicación)
* Siete canarios para Tlamanes
* _Xochicuicatl_ (nombre alternativo: cuadernillo)

.Maíz
* Advocaciones prehispánicas
** Chicomecoatl ("siete serpiente", semilla)
** Xilonen (elote)
** Cintli (mazorca)
* Advocaciones contemporáneas
** Chicomexóchitl ("siete flores", semilla) - siembra
** Elote - comestible
** Mazorca - levantamiento siembra

****
* Cualquier número puede ser sagrado [1, 2, 3, 4 y 5]
****

IMPORTANT: ¿El formato de ponencia justifica la omisión de referencias etnográficas?

IMPORTANT: Si el número siete se relaciona con los rumbos, ¿no debería corresponderle a cada cual un canario?

== [Análisis]
* Metodología de análisis paradigmático
.Canarios
* Inconsistencia entre la denominación [título o nombre del canario] y la acción (ej. mediodía)
* Inconsistencia entre la denominación y la forma musical
* Clasificaciones

** Grupo A +
Constantes, complejos, importantes e interpretados en momentos más significativos (al inicio, para la danza y ofrenda, al final) +
Relación de interdependencia (A depende de B y B depende de A): tipo melódico, denominación y acción ritual se presuponen mutuamente
*** El Canario
**** Connotación masculino
*** Xochipitzahuac
**** Connotación femenina
*** Chiconcanario
**** Masc. + Fem.
**** Unión de los dos modelos musicales anteriores

** Grupo B +
Inconsistentes en |estructura, título y momento|, variables, sencillos +
Relación de determinación (función   entre   una   constante   y   una   variable; Si está A también está B;  un término presupone al otro pero no viceversa): tipo melódico presupone denominación y acción ritual
*** Aves y otros actores (El tordo, La calandria, La golondrina)
*** Acciones (La despedida, El agradecimiento, La entrega, El recibimiento)
*** Eje temporal (Mediodía, Madrugada, Mañana)

IMPORTANT: ¿Hay alguna observación etológica que confirme la relación del tordo, la calandria o la golondrina con el ciclo de vida del maíz?

IMPORTANT: Si el grupo A sostiene una "relación de dependencia" con acciones rituales específicas (inicio del ritual, danza, ofrenda a la milpa), y otra de "connotación" con roles de género, ¿cuál es la relación entre las acciones rituales y los roles de género? ¿Cómo se agregan, además, las advocaciones sobre las etapas del maíz?

IMPORTANT: ¿Cómo es la "unión de modelos musicales" que caracteriza al Chiconcanario?

== [Conclusiones]
* La inconsistencia se explica por el proceso histórico: el ritual cae en desuso
* La consistencia del Grupo A se debe a su referencia directa al maíz
* «El hecho de que la música esté presente en los diversos espacios y secuencias que integran el Tlamanes, indica que, más que la de "ambientadora", adquiere una función trascendente de lo que podríamos entender como un "discurso cifrado", una forma de entablar ese contacto con las dedidades a las que se invoca.»

IMPORTANT: ¿Cómo pueden derivarse conclusiones históricas a partir de una metodología semiológica?
