= Sperber, D. - El simbolismo en general
:Author: Guillermo Mora Reguera
:Email: <guillermo.mora@fam.unam.mx>
:Date: octubre 2021
:Revision: 0
:toc:

== Prefacio

* [Las capacidades humanas de aprendizaje] están determinadas del mismo modo para todos los miembros de la especie; no son, pues, determinantes de las _variaciones_ culturales, sino sólo de la _variabilidad_ cultural. (p. 17)

* Los datos fundamentales para el estudio del saber tácito son datos intuitivos, son los juicios que los miembros de un grupo cultural expresan sistemáticamente sin desarrollar el argumento que los fundamenta.

* El simbolismo es un sistema de signos y, por ello, como la lengua propiamente dicha, depende de una semiología. Pero, en tanto que la lengua tiene señales propias que sólo se definen por su recíproca articulación y por su referencia al sentido lingüístico, el simbolismo utiliza como señales elementos, actos o enunciados, que existen y se interpretan también independientemente de él. (p. 26)

* Cuando se sabe cuánto tiempo, cuántas tensiones, pasiones y dedicaciones consume necesariamente el poner en marcha el menor ritual [o producción musical], ¿cómo creer que la incierta atribución de una interpretación semántica --y por lo tanto parafraseable en la lengua ordinaria al precio de un gasto de energía comparativamente nulo-- podría en modo alguno dar cuenta de la naturaleza del fenómeno? (pp. 29-30)

== IV. Simbolismo y saber

* «La mayor parte de las categorías del pensamiento comportan, pues, dos aspectos: uno semántico y otro enciclopédico» (p. 20)

* Saber semántico, enciclopédico y simbólico

* La metáfora también es "salvaje" (p. 22)

* «La exégesis de un símbolo es ella misma simbólica y constituye un desarrollo, no una interpretación, de aquello que pretende explicar» (p. 135)

* el saber simbólico tiene las representaciones [de los objetos] por objeto (p. 138)

* Hipótesis (p.142)

== V. El dispositivo simbólico

...

== Anotaciones

.Propiedades de lo simbólico
* ¿Es la parte irracional de de lo mental? ¿Es lo semiótico menos la lengua?

.Problemas entre signo y símbolo
