= Alegre, L. - El Vinuete
:Author: Guillermo Mora Reguera
:Email: <guillermo.mora@fam.unam.mx>
:Date: abril 2021 - agosto 2021
:Revision: 2
:toc:
:toc-title: Contenido

// "El vinuete: musica de muertos. Estudio etnomusicologico en una comunidad nahua de la huasteca potosina" de L. Alegre, disponible en https://tesiunam.dgb.unam.mx/ (el archivo para descargar se encuentra en el apartado de "Recurso electrónico - Texto completo", en su respectiva página). Esta tesis desarrolla varios temas de total importancia para el análisis etnomusicológico (sistema musical, semiología, análisis paradigmático, etnografía) por lo cual le dedicaremos, por lo pronto, dos sesiones. Siguiendo con las proposiciones teóricas, la próxima reunión revisaremos el capítulo VIII; y la siguiente los capítulos III y VII. Quedo atento a sus dudas y comentarios.

[bibliography]
== Referencias
* [[[lozano1979, Lozano, J. - Introducción a Lotman y la Escuela de Tartu (en Semiótica de la Cultura 1979)]]]
* [[[jauregui1986, Jáuregui, J, . El mariachi como elemento de un sistema folklórico (aparece en la página 30)]]]

== Capítulo III. El Vinuete en Chilocuil (p.43)

==== #Puntos generales
* Ceremonias comprendidas: Xantolo, Velación de cruz, Angelitos
** En otras comunidades, se emplea en las fiestas patronales [sistema de transformaciones]
* Referencia nativa: «música *sagrada* que se toca para los difuntos»
** Náhuatl: _mijkacuicatl_
** Su principal atributo es es provocar una gran tristeza a quien lo escucha

=== 1. El sistema musical de Chilocuil

==== #Definición de sistema musical
* Desde la voz _emic_, el Vinuete se comprende de manera *sistémica*: su constitución se define a partir de la posición que ocupa respecto a otras expresiones
** Esta posición se define a través de varios [*dominios*] como: instrumentación, carácter, ocasiones performativas, modos de ejecución
* Exposición parcial del sistema (p.44)
* [yellow-background]#Todo ello conforma un *espacio semiótico*, en el que los diversos elementos se vuelven *portadores de información codificada*, otorgando *identidad* y *sentido* a las distitnas prácticas musicales.#
****
En el campo de la etnomusicología, el concepto de _sistema musical_ ha sido aplicado al estudio de las estructuras sonoras. En nuestro caso, lo utilizaremos también para examinar el conjunto de ocasiones _performativas_. Por sistema musical, entendemos a un conjunto de hechos musicales dentro de una estructura que permite incorporar información codificada, a partir del juego entre *la semejanza y la diferencia*. El contraste de las características, permite que los rasgos que sobresalen por su disparidad se carguen de significado. Desde este punto de vista, los sonidos, las estructuras musicales, los géneros, las dotaciones musicales, y las ocasiones _performativas_, están dispuestos de acuerdo a ciertos códigos y formas gramaticales que funcionan como organizadores del fenómeno sonoro, constituyendo vínculos con otras dimensiones sociales. Se funda de esta manera, un gran [yellow-background]#sistema comunicativo#. (Camacho y González, inédito)
****
****
El sistema musical no es una estructura estática. Son muchos los aspectos que le dan movilidad provocando su transformación paulatina. [Intertextualidad del son _San Josentzin_] (p.47)
****
"[small]#Tenemos así las cuatro propiedades esenciales del simbolismo según la concepción estructuralista: un elemento no cobra valor simbólico más que en cuanto que se opone por lo menos a otro elemento. Una oposición simbólica es triplemente definida: 1) por su dominio, 2) por sus valores de oposición, 3) por su nivel de reducción. Las otras propiedades del simbolismo despejadas por el análisis estructural no hacen más que desarrollar estos cuatro puntos fundamentales.#"
-- Dan Sperber, El Simbolismo En General. Barcelona: Anthropos. 1988. (p. 83)

==== #Direccionalidad (divino/humano)[dominio]

.Direccionalidad de las ocasiones performativas
* *Divino*
. [underline]#Rituales agrícolas# +
Maíz y música de Canario
.. Petición de lluvias (depende del clima)
.. Ritual de siembra (sin fecha fija)
.. Tlamanes (cosecha)
. [underline]#Fiestas patronales# +
Danzas de _Xochitines_, _Cuaxompiates_, y _Armadillos_
.. Candelaria (2 de febrero)
.. San Felipe (patrono local, 5 de febrero)
.. San José (patrono de Tamán, 18 de marzo)
.. V. de Guadalupe (12 de diciembre)
. [underline]#Carnaval# +
Precede a la Cuaresma, _sones de Carnaval_, _Huapangos_ s/letra, _Cumbias_ s/letra
. [underline]#Semana Santa# +
No se toca música instrumental; sólo se realizan cantos litúrgicos en la iglesia. +
[¿Incluye Cuaresma?]
. [underline]#Ritos del ciclo de vida# +
Vinuete y cantos litúrgicos
.. Angelitos (muerte infantil, cuerpo presente)
.. Velación de cruz (nueve días pos-muerte, cruz de madera)

* *Humano*
. [underline]#Bautizos, Quince años y bodas# +
Huapango, Corrido, Cumbia, Canción norteña, Canción ranchera y Boleros +
Opcionalmente Canarios
. [underline]#Velación y entierro# +
Huapango, Corrido, Cumbia, Canción norteña, Canción ranchera y Boleros +
De cuerpo presente

* *Híbrido*
. [underline]#Xantolo# +
Sones de _Xoxos_ (anteriormente) +
Vinuetes (sancionados) +
Huapangos, cumbias, canciones rancheras, etc. (sancionados) +

IMPORTANT: La "direccionalidad" se refiere a la oposición "divino/humano" no a "muerte/vida".

==== #Análisis estructural del Vinuete
.Direccionalidad (en que se encuentra el Vinuete)
* Divino ->
** Vinuetes
** Sones de Xoxos
* Humano
** Huapangos
** Corridos
** Cumbias
** Etc.

.Cualidad emotiva de la música -> "a lo divino" (con la que se relaciona el Vinuete)
* Triste ->
** Vinuete
** (Cantos litúrgicos)
* Alegre
** Sones de Xoxos

.Comparación entre música -> "triste"
* Vinuete
** Trío huasteco
* Canto litúrgico
** Voz

.Función (de las ocasiones con Vinuete)
* Despedida (Vida -> Muerte)
** Velación de cruz
** Angelitos
* Recibimiento (Muerte -> Vida)
** Xantolo

.Direccionalidad de las "Despedidas"
* Divino
** Velación de cruz
** Angelitos
* Humano
** Velación y entierro

=== 2. Descripción general de las características musicales del Vinuete (p. 51)

* [underline]#Forma#
. Dos frases
. Tres frases
. Una frase
* [underline]#Fraseo#
. Ocho compases
. Seis compases
. Diez compases
. Nueve compases
. Siete compases
. Doce compases
* [underline]#Métrica# +
Ambos grupos con cambios métricos
. 2/4
. 6/8
* [underline]#Rítmica#
** Ambos
. Cuarto
. Octavo
. Dieciseisavo
** 2/4
. Octavo con puntillo + dieciseisavo
** 6/8
. Octavo + cuarto
. Octavo con puntillo + dieciseisavo
. Cuarto con puntillo
* [underline]#Tempo#
** 2/4
. 98 - 112
** 6/8
. 94 - 106
* [underline]#Tonalidades#
** Sol
** Re
** La
* [underline]#Armonía (posición)#
** Tónica (primera)
** Subdominante (tercera)
** Dominante (segunda)
*** V con sexta
** Acordes de paso
* [underline]#Rasgueo (azote)#
** 2/4 (el más típico)
. Azote doble
*** Adornos o tripleteados
. Azote simple
** 6/8 (similar al de huapangos y Canarios)
. Azote mixto
*** Zapateado (tomado del huapango)
* [underline]#Afinación# +
`No pertinente`

=== 3. Instrumentos

==== #Instrumentación

==== #Clasificación
* _Cuacacahuatl_ (palo hueco o cajón)
** Jarana
** Violín
** Huapanguera
* Tlapiltzalli (instrumentos de aliento)
** _Tepoztapiltzalli_ (metal)
** _Cuatlapiltzalli_ (madera)
** _Umetlapiltzalli_ (hueso)
* _Ayacaxtli_ (maraca, no-instrumento)

==== #Organología
[%autowidth]
|===
| *Náhuatl* | *Español* | *Parte del instrumento*
| _Ixpa_
| Frente
| Tapa de la caja armónica
| _Icuitlapa_ | Espalda | Fondo o parte inferior de la caja armónica
| _Ielxique_ | Costilla | Partes laterales de la caja armónica
| _Ixquecuayo_ | Pescuezo | Mango sobre el que se coloca el diapasón
| _Izonteco_ | Cabeza | Clavijero
| _Inacascuahuitl_
| _Inacas_: oídos +
_Cuahuitl_: madera +
Oídos de madera
| Clavijas
|===

=== #Simbología
* Partes del cuerpo en el ritual [small]#[_cfr._ González & Camacho - La música del maíz, Estudio etnomusicológico desde una perspectiva semiológica (2000)]#
* [yellow-background]#Mesoamérica#
* La anaología "anima" a los instrumentos
** Les merece cierta veneración
** Son capaces de "avisar"
* Ritual de adquisición de instrumento (sancionado)

== Capítulo V. Análisis paradigmático del Vinuete

=== Rasgos de análisis
.. Métrica (sugerido)
... 2/4
... 6/8
.. Forma (sugerido)
... Número de frases (de 1 a 3)
... Extensión de las frases (de siete a doce)
.. Armonía (sugerido)
... [Básica]
... Adornada
.. Azote ♫ (aplicado)
... Simple
... Doble
... Triplete
... Zapateado
.. Melodía
... Altura ♫ (aplicado)
... Ritmo ♫ (aplicado)

=== Criterio de análisis
* Criterio de repetición
* Ruwet: «repetición significa identidad entre segmentos repartidos en diversos sitios de una cadena sintagmática»

=== Paradigmas encontrados
* Paradigmas de [.underline]#rasgueo#
** 2/4
*** [big]#*I*# (simple o doble)
*** [big]#*II*# (tripleteado)
** 6/8
*** [big]#*III*# (zapateado)
* Paradigmas de [.underline]#ritmo#
** 2/4
*** [big]#*IV*#
*** [big]#*V*#
*** [big]#*VI*# (inicio de semifrase)
** 6/8
*** [big]#*VII*# (semifrases enteras)
*** [big]#*VIII*# (semifrases enteras)
* Paradigmas de [.underline]#altura#
*** [big]#*IX*# (inicio de semifrase)
*** [big]#*X*# (cierre de frase)
*** [big]#*XI*# (cierre de semifrase)
*** [big]#*XII*# (cierre de semifrase)

=== Corpus
. La llegada
. La entrada
. El encuentro
. La fiesta de los difuntos
. 1 y 2 de noviembre
. La Cruz
. El triste adiós
. El angelito
. La ofrenda
. Zapotéquetl
. El altar
. La despedida
. El angelito
. Flor de sempasúchil
. La entrada
. Adiós del muertito
. La santa cruz
. La llegada de los muertitos
. La despedida
. La entrada
. Zapotéquetl
. Adiós del muertito
. El angelito
. Flor de noviembre
. El caminito
. La entrada
. Siguiendo la cruz
. El angelito
. La ofrenda
. La cruz
. La entrada
. El recibimiento de los difuntos
. La cruz
. El angelito
. La entrada
. El altarcito
. El rosario
. Adiós del difunto
. La entrada
. La cruz
. El angelito
. La fiesta de los difuntos

.Conclusión (p. 175)
****
Si bien hay rasgos identitarios para cada grupo, no se puede definir al _vinuete_ como género a partir exclusivamente de las estructuras sonoras.
****

== Capítulo VII. Vinuete y Categorización (p.187)

=== 1. ¿Qué es el vinuete?

****
«A pesar del conocimiento específico de cada individuo y de las interpretaciones derivadas de la división social y sexual del trabajo, se observan aspectos comunes: el vinuete es música sagrada, es triste y es para los muertos. (p. 192)
****

=== 2. Tipo Cognitivo, Contenido Nuclear y Contenido Molar

* Tienen como objetivo «explicar el proceso cognitivo que va desde la percepción individual de una secuencia sonora hasta su categorización como vinuete»
. Tipo Cognitivo (TC)
.. Corresponde a la percepción semiótica (privada) del sujeto de la "imagen" de un objeto y la constitución de ésta en "tipo"
.. La imagen del objeto se compone de interpretantes
.. Interpretación: cada ocurrencia del objeto percibido se coteja con el tipo
. Contenido Nuclear (CN)
.. Proceso de socialización de los TTC
.. Homologación: emergencia de una «serie controlable de interpretantes que circunscriben el significado del objeto»
.. «Interpretantes públicos (comunes a todos los TTC)»
.. Orienta al TC, ofreciéndole "criterios para la identificación" de sus ocurrencias
.. Intersubjetivo y transmitido culturalmente
. Contenido Molar (CM)
.. «Conocimiento ampliado que comprende también nociones "no indispensables para el reconocimiento perceptivo.»
.. Sujeto competente

=== 3. [Problemas de las relaciones]

* No hay coincidencia entre:
** Nombres
** Secuencias sonoras
** Posición en el ritual
* Por lo anterior, «no existe una relación unívoca con nombres o funciones, que permita "fijarlos" cognitivamente a un contenido específico»
* TC de Individuos (TCI)
** Distinto del TC genérico (TCG)
** El TC de cada vinuete, queda asociado sólo a la imagen sonora
** No puede identificarse por medio de su nombre o posición
** No pueden ser interpretadas colectivamente

=== 4. TC, CN y CM en el caso de los vinuetes

* Para saber lo que el vinuete es, debe haber homologación entre en TCI y el TCG
* Esta homologación depende del reconocimiento de imágenes sonoras y de su ejecución en contexto pertinente
* CN se compone de tres interpretantes públicos
** Sagrado
** Muerte
** Tristeza
* [El vinuete no se identifica por sus TC (imagen sonora), sino por su CN (aprendido)]
* CM incluye
** Cualidades musicales
*** Rasgueos
*** Posiciones
** Elementos rituales
*** Comida para el altar

[%autowidth]
|===
|*CM =>* |=> *CN* <= |*<= CM*
|Cualidades musicales
|Triste, sagrado, muerto
|Comida para el altar
|*TC1*
|
|*TC2*
|===

=== 5. El sistema musical: un esquema cognitivo de la música como _hecho social total_

****
La música no es concebida como un fenómeno exclusivamente sonoro, sino como un hecho social total (Molino) [...] Lo que hace que todas las piezas que integran el repertorio de vinuetes sean agrupadas en una misma categoría, es la convención cultural que las ubica en el sistema musical de la comunidad [y no la imagen sonora]
****

=== 6. Conclusiones sobre la categorización del vinuete

.. Las diferencias de las estructuras sonoras hacen que cada pieza de vinuete constituya su propio TCI
.. Todos los vinuetes comparten un CN (sagrado, muerte, triste)
.. Sólo este CN permite homologar los TCI como TCG
.. «El CN no deriva de las estructuras sonoras, sino de la ubicación de éstas en el sistema musical»

****
«El vinuete es un género musical que no se define únicamente por las propiedades intrínsecas del objeto sonoro, sino por su cualidad emotiva, direccionalidad y función de los rituales en los que se ejecuta.»
****

== Capítulo VIII. La Ocasión Musical, Relaciones Intratextuales y Procesos de Significación

==== #Observaciones metodológicas y conceptos
* Inconsistencia enunciada entre testimonios y resultados analíticos ✓
* Varias iteraciones del mismo ritual (p. 203) ✓
* 5 categorías, pero ¿qué sucede con el resto de vinuetes? (p. 203)
* Sostenimiento de la facultad de "significado" (p. 205)
* Adaptación de la teoría a lo empírico
* "Forma de la expresión" ~ [configuración sonora del vinuete]

=== 1. Algunos conceptos de la teoría de Iuri Lotman (p. 206)

.[Antecedentes]
<<lozano1979, Lozano 1979>>

* «Máximo representante de la actual semiótica soviética»
* #Retoma Formalismo ruso y Lingüística estructural#
* «El folklore como forma de creación autónoma»
(Bogaritev y Jakobson)
.. No se da innovación lingüística sin que haya un #consenso social# que la acepte y la integre, y esto vale también para los otros #sistemas de comunicación#.
.. Cualquier sistema semiótico está sujeto a leyes semióticas generales y opera como código, pero tales #códigos están vinculados a comunidades específicas (del poblado al grupo étnico) del mismo modo que un lenguaje genera sus sub-códigos ligados a profesiones o actividades determinadas#.
.. El estudio de un código es estudio tanto de sus leyes sincrónicas como de la formación y transformación diacrónicas de estas leyes.
* #«Tipología de las culturas»#
* #Cultura: «información no hereditaria, que recogen, conservan y transmiten las sociedades humanas»#
* «#El signo en Lotman# no aparece  ya meramente como --según la concepción saussureana-- la relación de un significante y un significado, sino #como una unidad cultural entera. Y la cultura interviene y se caracteriza como un sistema (de sistemas) de signos organizados en un determinado modo#»
* Semiótica (p. 23)
** [.underline]#de la comunicación#, a la cual interesan los hechos construidos específicamente para comunicar
** [.underline]#semiótica de la significación# (Barthes y estructuralismo), para quienes #el objeto de la semiótica serían todos los sistemas de signos, todos los fenómenos significantes --desde el vestido a la comida--, aunque no supongan formas de comunicación voluntaria#, y que se plantea el estudio de cualquier fenómeno cultural en cuanto significante

.[La cultura según Lotman]
****
Como una lengua, es decir, un sistema semiótico ordenado de comunicación que sirve, por tanto, para transmitir información.
El lenguaje --como la cultura-- es:

. Un sistema de comunicación
. Que se sirve de signos
. Estos signos están organizados

Según estas características, se pueden distinguir tres tipos de lenguajes:

.. lenguajes naturales: ruso, español...
.. lenguajes artificiales: código de la carretera, lenguajes científicos, etc.
.. lenguajes secundarios: arte...

(<<lozano1979, Lozano 1979>>, p. 23)
****

.Semiósfera [small]#(p. 206)#
* «[...] _continuum_ semiótico, completamente ocupado por formaciones semióticas de diversos tipos y que se hallan en diversos niveles de organización»
* «Un espacio (abstracto) en el que "resultan posibles la realización de los procesos comunicativos y la producción de nueva información"»
* Totalidad cultural = semiósfera de semiósferas

IMPORTANT: ¿Cuál es la diferencia entre cultura, semiósfera y texto?

.Texto

* Definición
** La semiótica de la cultura concibe al texto como todo aquello que puede ser interpretado
** Para que algo pueda ser definido como texto, es necesario que esté codificado al menos dos veces

* Individualización y generalización

** Los textos no son interpretados siempre de la misma manera por todos los sujetos que participan de una cultura
** ¿Cómo analizar entonces la relación entre individuo y sociedad?
** Lotman: «el desarrollo de la cultura está ligado a la complicación de la estructura de la persona, a la individualización de los mecanismos codificadores de la información inherentes a ella»
** La individualización y #generalización# de los códigos son tendencias igualmente activas y constantes en la dinámica de la cultura
** El presente estudio se enfoca al segundo
** Si bien el estudio de las decodificaciones individuales puede ser abordado desde la semiótica, esta tarea recae principalmente en otras disciplinas como la psicología. (p.207)
** Consciencia individual -- texto -- cultura

* Funciones

. Grados de entendimiento del texto
... unívoco sin ambigüedad (señalización de tránsito)
... unívoco/ambiguo (texto en lengua natural)
... ambiguo sin univocidad (texto poético)
.... _Paradoja comunicativa_
.... _Poliglotismo cultural y semiótico_
.... Heterogeneidad del espacio semiótico

. Sentido
.. Requiere al menos dos codificaciones (poliglotismo)
.. La relación entre códigos o lenguajes que permite la generación de sentido es la #_equivalencia convencional_#
.. «Los textos que generan sentido, presentan en su interior dos o más #textos cifrados en distintos lenguajes#» (p. 208)
.. Hace al texto intermediario entre Ind. y Cult. a través de una relación dialógica

. Memoria
.. Programa mnemotécnico
.. Opera a través del texto-código

.Texto-código del vinuete

.. Modelo estructural
. De la palabra (lo verbal)
. Del espacio (a través de oposiciones: cultu/inculto; vivo/muerto; seguridad/peligro)
* En el caso del vinuete, la estructura del espacio es definida por la "direccionalidad" (espacio sagrado/espacio humano)

.. Aplicación al caso del vinuete:
* «Cada realización [del ritual] es un todo construido sintagmáticamente, pero al mismo tiempo presenta propiedades paradigmáticas que comparte con todos los [otros] rituales del mismo tipo [y] los subtextos que lo integran y que están cifrados en diferentes lenguajes,pueden ser leídos no sólo linealmente sino paradigmáticamente.»` (p. 209)
* Música y espacio en el caso del vinuete
* Intratextualidad
«El conjunto de relaciones al interior de un texto, que exhiben una equivalencia convencional entre las estructuras [códigos] de los lenguajes que lo constituyen, a través de un mecanismo de traducción intersemiótica [equivalencia convencional]» (p.210)

=== 2. El _vinuete_ en el marco de las ocasiones musicales

==== 2.1. El sistema musical como sonósfera
* «El mínimo generador [de sentido] operante no es un texto aislado, sino un texto en interacción con otros textos y con el medio semiótico.» (p. 211)
* «La necesidad de recurrir [cfr. p. 43] a operaciones de distinción y semejanza para explicar el contenido asociado al _vinuete_, pone de manifiesto que el mínimo generador operante de sentidos [en las diversas ceremonias (textos) de Chilocuil] es su interacción con otros textos y con el medio semiótico del cual forman parte.» (p. 211)

==== 2.2. El espacio-tiempo de las ocasiones performativas del _vinuete_
.Temporalidad sagrada
* Retorno al inicio
* Ciclos
* Muerte
* Distinta u opuesta a la cotidianidad

.Objetos funcionando como signos sagrados
* Altar, ofrenda, cruz
* _Vinuetes_

****
«La interrelación [intersemiosis, equivalencia convencional] entre las estructuras [códigos] del lenguaje musical y las del lenguaje de las relaciones espaciales [modelo estructural del espacio] confiere al _vinuete_, a través de un proceso de traducción intersemiótica, uno de los contenidos que se le adjudican colectivamente: el de la sacralidad» (p. 215)
****

=== 3. Relaciones _intratextuales_ entre los lenguajes musical, visual y verbal en los rituales de _Velación de cruz_ y _Xantolo_

Análisis de la generación de sentido en dos textos (Velación de cruz y Xantolo) a partir de tres variables intersemióticas

==== 3.1. Análisis de las relaciones _intratextuales_ en el ritual de _Velación de cruz_

.Rasgos pertinentes
. Nombre
****
«La asignación de nombres a secuencias sonoras [piezas] pone de manigfiesto el contenido que se confiere a estas últimas.» (p. 220)
****
. Músicos
. Fecha y Hora
. Contexto [ritual]
****
«Inserción de la música en el texto ritual» (p.220)
****
===== 3.1.1. Recibimiento de la cruz
. Signos sagrados
.. Cruz
.. Arco
.. Aguardiente y copas
.. Flores (guirnaldas)
.. Comida (panes)
. Gestos como lenguaje visual
.. Arrodillamiento
.. Ofrecimiento de ofrenda
.. Transferencia de cruz
.. Llanto
. Lenguaje verbal
.. Rezos
.. Diálogos pertinentes
. Título de _vinuetes_ como lenguaje musical
.. _El recibimiento_
.. _El encuentro_
.. _El brindis_
.. _La Santa cruz_
.. Calificados como "música triste"

IMPORTANT: En este caso, por lenguaje musical no se entiende la estructura (melódica, rítmica, métrica, armónica u organoloógica) que subyace a las "secuencias sonoras", sino el título de la pieza. El análisis musical no logró evidenciar consistencias que permitieran referir al "lenguaje musical" desde estas perspectivas.

===== 3.1.5. La no coincidencia entre las unidades discretas de los diferentes lenguajes que constituyen al texto

«No siempre la segmentación en unidades discretas de los lenguajes que [conforman al texto]se da de manera equivalente.» (p. 228) La unidad |pieza musical| no se corresponde necesariamente con las |acciones simultáneas|, sino con la |secuencia ritual| completa. En otros casos, ni siquiera existe esta última coincidencia. Esta inconsistencia la resuelve la cualidad paradigmática meta-lineal y meta-secuencial del texto-código.

==== 3.2. Intertextualidad
Los nombres (títulos) de ciertas secuencias sonoras (piezas musicales) interpretadas en determinados rituales aluden a otros. Esta y otras equivalencias convencionales en las ceremonias de _Xantolo_, _Velación de cruz_ y _Angelitos_ evidencian que son generadoras del mismo sentido: muerte. «Así, los _vinuetes_ se constituyen en vehículos sígnicos que transportan significado de un ritual a otro. La música es uno de varios elementos que trazan el camino de los muertos: de _Angelitos_ y _Velación de cruz_ a _Xantolo_; de la vida a la muerte y de la muerte a la vida.»

==== 4. Conclusiones sobre la ocasión musical
****
«Los nombres atribuidos a los _vinuetes_ evidencian la cualidad emergente de los significados en momentos concretos de ejecución, como resultado de un mecanismo de traducción intersemiótica a través del cual se establece una equivalencia convencional entre las estructuras de los lenguajes musical, visual y verbal»
****
****
«La descripción [...] de la trayectoria del movimiento dibujado por un gesto o de la forma que presenta un objeto, nos dice pro sí misma poco acerca de su signficiado. Éste sólo puede ser mejor comprendido si se atiende al texto en su conjunto, al ritual como realización simbólica que condensa una serie de aspectos relacionados con la cosmovisión»
****
****
«La práctica musical del _vinuete_, es decir, el hecho sonoro, sus ocasiones de ejecución y las conductas y creencias asociadas, se constituye como una práctica cultural que expresa el modo en el que los habitantes de Chilocuil interpretan la muerte.»
****
