= Nava, F. - Danzas con reverencias para una conquista gentil
:Author: Guillermo Mora Reguera
:Email: <guillermo.mora@fam.unam.mx>
:Date: octubre 2021
:Revision: 0
:toc:

== [Introducción]

.Descripción del objeto
* «Conjunto de danzas populares» presentes en México con tema de confrontación inter-étnica entre conquistadores y gentiles
* Motivos
** Europeos
*** Los doce pares de Francia
*** Moros y Cristianos
** Derrota del imperio azteca
** Amalgamas
* Elementos formales
** Parlamentos o coloquios
*** Estructura de versos
** Patrones organizativos
*** Sistema de mayordomías
*** Calendario de eventos
** Música
*** Melodía
*** Armonía
*** Ritmo

.Objetivos
* Demostrar la existencia de una constante musical...
* Identificar dicha constante a través de la notación
* Interpretar la presencia de dicha constante
** «Señalar algunas rutas sugestivas que nos aproximen a los procesos que gobiernan la apreciación artística [...] por una colectividad de personas» (p. 302)
** «La música carece de un significado intrínseco; es la gente que la hace --o la reproduce-- quien le da cierta apreciación, por demás, subjetiva.»
* «Esbozar el vínculo objetivo y socializado entre un grupo sonoro particular y un aspecto específico de un tipo de danza»

.Consideraciones analíticas
* Fusión de la música con
** Coreografía
** Apelativos (de las partes musicales)
* Aspectos conceptualess
** Historia
** Organología
** Símbolos
** Danza
* «Unidades musicales»
** En lugar de _sones de danza_
** Para referir también otra música para la danza: canciones, polcas, pasos, tonadas, toque militar, etcétera...
** Para referir música sin función coreográfica: canatos, alabanzas
* Análisis basado en partituras (p. 306)
** Principalmente fuentes documentales
* Los criterios y procedimientos se han diseñado para «abstraer un esquema de la estructura del repertorio musical»

.Dimensiones formales (análisis formal)
.. Estructura del repertorio musical
... «Toda danza cuenta con un conjunto de unidades musicales» o repertorio para secciones con y sin coreografía
... «Es la disposición de las unidades musicales que corresponde a la puesta en práctica de una evolución completa del proceso dancístico, ya estando situado el grupo en su área de ejecución coreográfica.» (p. 307)
... Éste puede ser finito, para sistemas cerrados o potencialmente infinito, para sistemas abiertos
... «Se somete a una estructura [...] que regulariza la correspondencia entre» música y otros elementos
.. Estructura interna de las unidades musicales (piezas)
... En función de su «extensión y contornos melódicos»
... «Patrones melódicos»
... «Esquema armónico»
.. Dos (tipos) de unidad musical
... [yellow-background]#"Desarrollada" (UMD)#
.... Melodía (definida)
.... Patrón rítmico regular
.... Armonía estable
.... Nombradas
... Constante musical

.Selección del corpus de análisis
* Definido por tema "Danzas de conquista"
** Comprenden dos bandos antagónicos
* Elude el problema de denominación

== [Danzas]

.Criterios de análisis
. Número de unidades musicales de (tipo) "desarrolladas"
.. Determinado
.. No determinado
. Giro melódico idéntico de ppio. y fin ("vuelta")

.1 Arcos, Mecos, o Apaches, Danza de
* 'Patrón de alternancia I' [(Reverencia + UMDx + Reverencia) + Parlamentos]

.2 Arcos, Danza de los
* Se suponen varios aspectos para formular el patrón ||:Reverencia + UMD:|| + Reverencia
* 'Patrón de alternancia II' ('Espejo historial')

.3 Caporales, Danza de
* Seis UMD y Reverencia, se ignora el ordenamiento

.4 Conquista, Danza de la
* 'Patrón de alternancia I' (en 12 de las 19 UMD)

.5 Chichimecas contra franceses
* 17 UMDs
* Reverencias inicial (A) y final (B)
* Variación del 'Patrón de alternancia I' (Reverencia A + UMDx + Reverencia B)

.6 David y Goliat, Danza de
* 11 UMDs
* Reverencia = UMD
* 'Patrón de alternancia II' ('Espejo historial')

.7 Doce pares de Francia, Danza de los
* 7 UMDs
* Variación del 'Patrón de alternancia I' (Reverencia A + UMDx + Reverencia B)
* «Además, la reverencia A también se ejecuta de manera aislada, haciendo las veces de puente para enlazar algunos diálogos»

.8 Espejo historial, Danza del; Historia de Carlos Mangos y de los Doce Pares de Francia
* 6 UMDs (posiblemente)
* 'Patrón de alternancia II' Reverencia + UMD1 + Reverencia + ||:UMDx + Reverencia (+ Parlamento):||
* Reverencia = puente

.9 Infantería, Danza de; o Danza de 'a pie'
* ~7 UMDs
* Variante del 'Patrón de alternancia II'

.10 Danza mariana
* =<10 UMDs
* 'Patrón de alternancia I'

.11 Maromeros, Danza de
* UMDs indeterminado
* 'Patrón de alternancia I'

.12 Moctezuma, Danzas de
* 15 UMDs
* 'Patrón de alternancia I'

.Morisma
* 15 UMDs
* Variante del 'Patrón de alternancia II'

.Moros, Danza de
* 5 UMDs
* Reverencias alternativas (A) y (B)
* Variante del 'Patrón de alternancia I'

.Paloteros, Danza de los
* 11 UMDs
* Reverencia (sugerida por unas cuantas notas) como puente ocasional, nunca conclusiva
* Variante del 'Patrón de alternancia II'

.Rayados, Danza de los
* UMDs indeterminadas
* 'Patrón de alternancia I'

.Tocotines, Danza de los
* UMDs definidas (?)
* Reverencia = puente; no se usa ni para iniciar ni para concluir
* Variante del 'Patrón de alternancia II'

.Tolteca, Danza; o Danza Chichimeca
* UMDs indefinido
* 'Patrón de alternancia I

== Reverencia (unidad constante musical)
.Lo constante
* Es la constante musical del conjunto de danzas de conquista
* Señalador musical y coreográfico
* Contrasta (melodía, armonía, ritmo) con las unidades musicales desarrolladas
** «Es caprichoso giro o breve visaje» (p. 309)
* Todas las unidades musicales «comienzan y terminan con un giro melódico idéntico» (p. 308)
** «Se halla restringida a un momento particular que se repite al interior de la danza» (p. 304)
* No siempre recibe título
* Reconocida en lo _emic_ como un «fragmento complementario, en oposición a la noción integral que despiertan las UMD de la danza; por ello, aparenta recibir una estimación menor» (p. 309)

.Lo variable
* Melodía no definida
* Patrón métrico léxico
* Inconsistencia en lo armónico (bien determinadas o con extrema libertad)
* Identificada en lo _emic_ como una "cierta unidad" o "cuasi-unidad"
* En 'Danza de David y Goliat' aparece como UMD

IMPORTANT: ¿Otras danzas con temáticas distintas a la conquista comportan también constantes musicales similares a la reverencia? (Sistema de transformaciones de lo musical, coreográfico y performativo)

IMPORTANT:

== Interpretación histórica
* Sujetos militares = Sujetos danzantes
* Toque de guerra -> escaramuza y pseudo combates -> reverencia

.Sistemas auditivos
* De la milicia mesoamericana e ibérica hacia el primer cuarto del s. XVI
* «La virtud de los toques marciales era la de despertar una noción de grupo organizado...»

.Mesoamericano
** Cornetes de caracol ('toques de avance')
** Cornetes de corteza
** Huéhuetl
** Ocarinas
** Trompetas de guaje

.Español
* Cascabeles (caballos)
* Bandas militares
* Pífanos de carrizo
* Flautas transversales y rectas

.Alianzas
* Complemento de de "códigos sonoros"

****
«A la luz de lo anterior, los antecedentes de la "reverencia" pueden ser detectados tanto en la tradición europea de las danzas-drama con argumentos de combate, así como en la correspondiente costumbre mesoamericana [...] Dentro de la estructura del repertorio musical, dicha constante anuncia y/o concluye la ejecución de las UMD; pero, más allá de eso, es evidente que se trata de una especie de toque militar.» (pp. 329-330)
****

.Forma musical de la reverencia
* El soldado-músico "muy probablemente" descuidaba el patrón rítmico por la "tensión" del combate
* Su comportamiento melódico y la imitación del aerófono (4tas y 5tas) sugiere un origen europeo


.Preguntas abiertas
* ¿Hay danzas en las que a cada bando le corresponda una reverencia que se distingue en instrumento y ritmo del otro?
